import {
  Listing,
  ViewingSlot,
  Lead,
  ConversationMessage,
  Viewing,
  KnowledgeSource,
  AgentRule,
} from "./types";

export const listings: Listing[] = [
  {
    id: "klcc-residences-3br",
    name: "KLCC Residences",
    title: "KLCC Residences",
    location: "Jalan Sultan Ismail, Kuala Lumpur",
    price: 780000,
    priceDisplay: "RM780,000",
    currency: "MYR",
    beds: 3,
    bedrooms: 3,
    baths: 2,
    bathrooms: 2,
    sqft: 1180,
    sizeSqft: 1180,
    description: "High-floor city-view unit, 8 minutes from KLCC.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    badge: "Best Match",
    propertyType: "Condominium",
    status: "available",
  },
  {
    id: "bukit-bintang-suite-3br",
    name: "Bukit Bintang Suite",
    title: "Bukit Bintang Suite",
    location: "Bukit Bintang, Kuala Lumpur",
    price: 795000,
    priceDisplay: "RM795,000",
    currency: "MYR",
    beds: 3,
    bedrooms: 3,
    baths: 2,
    bathrooms: 2,
    sqft: 1120,
    sizeSqft: 1120,
    description: "Walkable to retail, dining, and transit.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    badge: "New Listing",
    propertyType: "Condominium",
    status: "available",
  },
  {
    id: "verde-mont-kiara-3br",
    name: "Verde Mont Kiara",
    title: "Verde Mont Kiara",
    location: "Mont Kiara, Kuala Lumpur",
    price: 1180000,
    priceDisplay: "RM1,180,000",
    currency: "MYR",
    beds: 3,
    bedrooms: 3,
    baths: 2,
    bathrooms: 2,
    sqft: 1250,
    sizeSqft: 1250,
    description: "Low-density residence with garden views.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
    badge: "Premium",
    propertyType: "Condominium",
    status: "available",
  },
  {
    id: "bangsar-urban-loft",
    name: "Bangsar Urban Loft",
    title: "Bangsar Urban Loft",
    location: "Bangsar, Kuala Lumpur",
    price: 920000,
    priceDisplay: "RM920,000",
    currency: "MYR",
    beds: 2,
    bedrooms: 2,
    baths: 2,
    bathrooms: 2,
    sqft: 980,
    sizeSqft: 980,
    description: "Modern loft near Bangsar Shopping Centre.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
    badge: "Trendy",
    propertyType: "Loft",
    status: "available",
  },
  {
    id: "setapak-family-residence",
    name: "Setapak Family Residence",
    title: "Setapak Family Residence",
    location: "Setapak, Kuala Lumpur",
    price: 650000,
    priceDisplay: "RM650,000",
    currency: "MYR",
    beds: 4,
    bedrooms: 4,
    baths: 3,
    bathrooms: 3,
    sqft: 1400,
    sizeSqft: 1400,
    description: "Spacious terrace with schools and LRT nearby.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    badge: "Family",
    propertyType: "Terrace house",
    status: "available",
  },
  {
    id: "cheras-starter-condo",
    name: "Cheras Starter Condo",
    title: "Cheras Starter Condo",
    location: "Cheras, Kuala Lumpur",
    price: 485000,
    priceDisplay: "RM485,000",
    currency: "MYR",
    beds: 1,
    bedrooms: 1,
    baths: 1,
    bathrooms: 1,
    sqft: 650,
    sizeSqft: 650,
    description: "Affordable first-home option with MRT access.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    badge: "Starter",
    propertyType: "Condominium",
    status: "available",
  },
  {
    id: "pj-garden-terrace",
    name: "Petaling Jaya Garden Terrace",
    title: "Petaling Jaya Garden Terrace",
    location: "Petaling Jaya, Selangor",
    price: 1050000,
    priceDisplay: "RM1,050,000",
    currency: "MYR",
    beds: 4,
    bedrooms: 4,
    baths: 3,
    bathrooms: 3,
    sqft: 1550,
    sizeSqft: 1550,
    description: "Garden-facing terrace in a mature neighbourhood.",
    image: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=80",
    badge: "Spacious",
    propertyType: "Terrace house",
    status: "available",
  },
  {
    id: "cyberjaya-smart-suite",
    name: "Cyberjaya Smart Suite",
    title: "Cyberjaya Smart Suite",
    location: "Cyberjaya, Selangor",
    price: 420000,
    priceDisplay: "RM420,000",
    currency: "MYR",
    beds: 1,
    bedrooms: 1,
    baths: 1,
    bathrooms: 1,
    sqft: 620,
    sizeSqft: 620,
    description: "Smart-layout unit near tech campuses.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    badge: "Smart",
    propertyType: "Condominium",
    status: "available",
  },
  {
    id: "shah-alam-family-residence",
    name: "Shah Alam Family Residence",
    title: "Shah Alam Family Residence",
    location: "Shah Alam, Selangor",
    price: 880000,
    priceDisplay: "RM880,000",
    currency: "MYR",
    beds: 4,
    bedrooms: 4,
    baths: 3,
    bathrooms: 3,
    sqft: 1450,
    sizeSqft: 1450,
    description: "Spacious 4-bedroom terrace near schools and highway.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    badge: "Family",
    propertyType: "Terrace house",
    status: "available",
  },
];

export function getViewingSlots(): ViewingSlot[] {
  const now = new Date();
  return [
    {
      id: "slot-tomorrow-15",
      label: "Tomorrow, 3:00 PM",
      appointmentAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 15, 0).toISOString(),
    },
    {
      id: "slot-wednesday-11",
      label: "Wednesday, 11:00 AM",
      appointmentAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 3, 11, 0).toISOString(),
    },
    {
      id: "slot-thursday-17",
      label: "Thursday, 5:00 PM",
      appointmentAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 4, 17, 0).toISOString(),
    },
  ];
}

const baseTime = Date.now();

function t(minutesAgo: number) {
  return new Date(baseTime - 1000 * 60 * minutesAgo).toISOString();
}

function findListing(id: string): Listing {
  return listings.find((l) => l.id === id) || listings[0];
}

const slots = getViewingSlots();

export const allViewings: Viewing[] = [
  {
    bookingId: "bkg-001",
    id: "bkg-001",
    confirmed: true,
    appointmentAt: slots[0].appointmentAt,
    leadId: "aisha-rahman",
    listingId: "klcc-residences-3br",
    slotId: slots[0].id,
    listing: findListing("klcc-residences-3br"),
    slot: slots[0],
    channel: "whatsapp",
    status: "confirmed",
  },
  {
    bookingId: "bkg-002",
    id: "bkg-002",
    confirmed: false,
    appointmentAt: slots[1].appointmentAt,
    leadId: "daniel-tan",
    listingId: "verde-mont-kiara-3br",
    slotId: slots[1].id,
    listing: findListing("verde-mont-kiara-3br"),
    slot: slots[1],
    channel: "whatsapp",
    status: "pending",
  },
  {
    bookingId: "bkg-003",
    id: "bkg-003",
    confirmed: true,
    appointmentAt: slots[2].appointmentAt,
    leadId: "farah-aziz",
    listingId: "shah-alam-family-residence",
    slotId: slots[2].id,
    listing: findListing("shah-alam-family-residence"),
    slot: slots[2],
    channel: "whatsapp",
    status: "confirmed",
  },
];

const aishaRecommended = listings.filter(
  (l) => l.id === "klcc-residences-3br" || l.id === "bukit-bintang-suite-3br"
);

const aishaConversation: ConversationMessage[] = [
  { id: "a-1", conversationId: "aisha-rahman", sender: "lead", channel: "whatsapp", content: "Hi, I’m looking for a 3-bedroom condo near KLCC, budget under RM800k.", createdAt: t(30), deliveryStatus: "read" },
  { id: "a-2", conversationId: "aisha-rahman", sender: "ai", channel: "whatsapp", content: "Hi Aisha 👋 I can help with that. Are you already pre-approved for financing, or would you be buying with cash?", createdAt: t(29), deliveryStatus: "read" },
  { id: "a-3", conversationId: "aisha-rahman", sender: "lead", channel: "whatsapp", content: "Yes, approved up to RM850k.", createdAt: t(27), deliveryStatus: "read" },
  { id: "a-4", conversationId: "aisha-rahman", sender: "ai", channel: "whatsapp", content: "Perfect. Do you prefer KLCC, Bukit Bintang, or Mont Kiara? And when are you hoping to move?", createdAt: t(26), deliveryStatus: "read" },
  { id: "a-5", conversationId: "aisha-rahman", sender: "lead", channel: "whatsapp", content: "KLCC or Bukit Bintang. Within 2 months.", createdAt: t(24), deliveryStatus: "read" },
  {
    id: "a-6",
    conversationId: "aisha-rahman",
    sender: "ai",
    channel: "whatsapp",
    content: "Thanks, Aisha. I found two 3-bedroom condos that match your budget, preferred areas, and timeline.",
    createdAt: t(22),
    deliveryStatus: "read",
    metadata: { listings: aishaRecommended, actionType: "listing_match" },
    actions: ["Matched 2 listings", "Lead qualified"],
  },
  { id: "a-7", conversationId: "aisha-rahman", sender: "lead", channel: "whatsapp", content: "I like KLCC Residences.", createdAt: t(18), deliveryStatus: "read" },
  {
    id: "a-8",
    conversationId: "aisha-rahman",
    sender: "ai",
    channel: "whatsapp",
    content: "Excellent choice. I can arrange a viewing with the listing agent. Which time works best for you?",
    createdAt: t(17),
    deliveryStatus: "read",
    metadata: { slots, actionType: "listing_match" },
  },
  { id: "a-9", conversationId: "aisha-rahman", sender: "lead", channel: "whatsapp", content: "Tomorrow, 3:00 PM.", createdAt: t(15), deliveryStatus: "read" },
  {
    id: "a-10",
    conversationId: "aisha-rahman",
    sender: "ai",
    channel: "whatsapp",
    content: "✅ Viewing confirmed for KLCC Residences tomorrow at 3:00 PM. I’ve sent the confirmation and calendar details here on WhatsApp.",
    createdAt: t(14),
    deliveryStatus: "read",
    metadata: { booking: allViewings.find((v) => v.bookingId === "bkg-001"), actionType: "booking" },
    actions: ["Viewing booked"],
  },
];

const danielConversation: ConversationMessage[] = [
  { id: "d-1", conversationId: "daniel-tan", sender: "lead", channel: "whatsapp", content: "Hi, I want a 3-bedroom condo in Mont Kiara, budget around RM1.2M.", createdAt: t(300), deliveryStatus: "read" },
  { id: "d-2", conversationId: "daniel-tan", sender: "ai", channel: "whatsapp", content: "Hi Daniel 👋 Thanks for reaching out. Are you pre-approved for financing, and when are you hoping to move?", createdAt: t(295), deliveryStatus: "read" },
  { id: "d-3", conversationId: "daniel-tan", sender: "lead", channel: "whatsapp", content: "Pre-approved up to RM1.3M. Looking to move within 3 months.", createdAt: t(280), deliveryStatus: "read" },
  {
    id: "d-4",
    conversationId: "daniel-tan",
    sender: "ai",
    channel: "whatsapp",
    content: "Great — I have several 3-bedroom condos in Mont Kiara within your budget. Can you share more photos?",
    createdAt: t(270),
    deliveryStatus: "read",
    metadata: { listings: [findListing("verde-mont-kiara-3br")], actionType: "listing_match" },
  },
  { id: "d-5", conversationId: "daniel-tan", sender: "lead", channel: "whatsapp", content: "Can you share more photos?", createdAt: t(8), deliveryStatus: "delivered" },
];

const nurulConversation: ConversationMessage[] = [
  { id: "n-1", conversationId: "nurul-izzati", sender: "lead", channel: "whatsapp", content: "Hi, I’m considering selling my condo in Bangsar.", createdAt: t(900), deliveryStatus: "read" },
  { id: "n-2", conversationId: "nurul-izzati", sender: "ai", channel: "whatsapp", content: "Hi Nurul 👋 I can help you list it. What’s the address, and what asking price are you targeting?", createdAt: t(890), deliveryStatus: "read" },
  { id: "n-3", conversationId: "nurul-izzati", sender: "lead", channel: "whatsapp", content: "It’s a 3-bedroom condo, asking around RM1.5M.", createdAt: t(880), deliveryStatus: "read" },
];

const marcusConversation: ConversationMessage[] = [
  { id: "m-1", conversationId: "marcus-lim", sender: "lead", channel: "whatsapp", content: "Is it near MRT?", createdAt: t(2100), deliveryStatus: "read" },
  { id: "m-2", conversationId: "marcus-lim", sender: "ai", channel: "whatsapp", content: "Hi Marcus 👋 Yes — several rental units near Bukit Bintang are walking distance to MRT. What’s your monthly budget and move-in timeline?", createdAt: t(2090), deliveryStatus: "read" },
];

const farahConversation: ConversationMessage[] = [
  { id: "f-1", conversationId: "farah-aziz", sender: "lead", channel: "whatsapp", content: "Saya cari rumah 4 bilik dekat Shah Alam, bajet bawah RM900k.", createdAt: t(120), deliveryStatus: "read" },
  { id: "f-2", conversationId: "farah-aziz", sender: "ai", channel: "whatsapp", content: "Hai Farah 👋 Boleh. Adakah anda sudah mendapat kelulusan pinjaman? Saya akan carikan pilihan rumah 4 bilik yang sesuai dengan bajet anda.", createdAt: t(115), deliveryStatus: "read" },
];

export const initialLeads: Lead[] = [
  {
    id: "aisha-rahman",
    name: "Aisha Rahman",
    phoneMasked: "+60 12-**** 4821",
    source: "WhatsApp",
    channel: "whatsapp",
    intent: "buyer",
    location: "KLCC / Bukit Bintang",
    preferredAreas: ["KLCC", "Bukit Bintang"],
    budget: "Under RM800k",
    budgetLabel: "Under RM800k",
    budgetMax: 800000,
    propertyType: "Condo",
    bedrooms: 3,
    financing: "approved",
    timeline: "Within 2 months",
    score: 85,
    scoreLabel: "Hot",
    status: "booked",
    conversationStatus: "ai_handling",
    assignedAgent: "Sarah Lee",
    aiSummary: "Aisha is a finance-approved buyer seeking a 3-bedroom condo near KLCC or Bukit Bintang. She has a budget of RM800k and plans to move within two months. She selected KLCC Residences and confirmed a viewing tomorrow at 3:00 PM.",
    nextBestAction: "Send property brochure before the viewing and offer an AI call for questions.",
    callStatus: "not_requested",
    lastActivity: aishaConversation[aishaConversation.length - 1].createdAt,
    qualification: {
      budgetMax: 800000,
      budgetLabel: "Under RM800k",
      location: "KLCC / Bukit Bintang",
      preferredAreas: ["KLCC", "Bukit Bintang"],
      propertyType: "Condo",
      bedrooms: 3,
      financing: "approved",
      timelineDays: 60,
      timeline: "Within 2 months",
    },
    conversation: aishaConversation,
    recommendedListings: aishaRecommended,
    bookedViewing: allViewings.find((v) => v.bookingId === "bkg-001"),
    timelineEvents: [
      { id: "te-a-1", type: "inquiry", title: "WhatsApp inquiry received", createdAt: t(30) },
      { id: "te-a-2", type: "ai_response", title: "AI responded in 8 seconds", createdAt: t(29) },
      { id: "te-a-3", type: "qualification", title: "Financing eligibility captured", createdAt: t(27) },
      { id: "te-a-4", type: "listing_match", title: "Two matching listings shared", createdAt: t(22) },
      { id: "te-a-5", type: "viewing_booked", title: "KLCC Residences selected", createdAt: t(18) },
      { id: "te-a-6", type: "viewing_booked", title: "Viewing confirmed: Tomorrow 3:00 PM", createdAt: t(14) },
    ],
  },
  {
    id: "daniel-tan",
    name: "Daniel Tan",
    phoneMasked: "+60 17-**** 1102",
    source: "WhatsApp",
    channel: "whatsapp",
    intent: "buyer",
    location: "Mont Kiara",
    preferredAreas: ["Mont Kiara"],
    budget: "RM1.2M",
    budgetLabel: "RM1.2M",
    budgetMax: 1200000,
    propertyType: "Condo",
    bedrooms: 3,
    financing: "approved",
    timeline: "Within 3 months",
    score: 78,
    scoreLabel: "Warm",
    status: "qualified",
    conversationStatus: "ai_handling",
    assignedAgent: undefined,
    aiSummary: "Daniel is a pre-approved buyer looking for a 3-bedroom condo in Mont Kiara with a budget of RM1.2M. He is asking for more photos before selecting a viewing time.",
    nextBestAction: "Share additional photos and offer a viewing slot.",
    callStatus: "not_requested",
    lastActivity: danielConversation[danielConversation.length - 1].createdAt,
    qualification: {
      budgetMax: 1200000,
      location: "Mont Kiara",
      preferredAreas: ["Mont Kiara"],
      propertyType: "Condo",
      bedrooms: 3,
      financing: "approved",
      timelineDays: 90,
      timeline: "Within 3 months",
    },
    conversation: danielConversation,
    recommendedListings: [findListing("verde-mont-kiara-3br")],
    bookedViewing: allViewings.find((v) => v.bookingId === "bkg-002"),
    timelineEvents: [
      { id: "te-d-1", type: "inquiry", title: "WhatsApp inquiry received", createdAt: t(300) },
      { id: "te-d-2", type: "qualification", title: "Budget and financing captured", createdAt: t(280) },
      { id: "te-d-3", type: "listing_match", title: "Mont Kiara listing shared", createdAt: t(270) },
    ],
  },
  {
    id: "nurul-izzati",
    name: "Nurul Izzati",
    phoneMasked: "+60 13-**** 7739",
    source: "WhatsApp",
    channel: "whatsapp",
    intent: "seller",
    location: "Bangsar",
    preferredAreas: ["Bangsar"],
    budget: "RM1.5M",
    budgetLabel: "Asking RM1.5M",
    budgetMax: 1500000,
    propertyType: "Condo",
    bedrooms: 3,
    financing: "unknown",
    timeline: "Flexible",
    score: 64,
    scoreLabel: "Warm",
    status: "new",
    conversationStatus: "ai_handling",
    assignedAgent: "Adam Ng",
    aiSummary: "Nurul is a seller in Bangsar with a 3-bedroom condo and an asking price of RM1.5M. PropertyLah captured the listing intent and is gathering unit details for agent review.",
    nextBestAction: "Collect unit details and arrange a valuation appointment.",
    callStatus: "not_requested",
    lastActivity: nurulConversation[nurulConversation.length - 1].createdAt,
    qualification: {
      budgetMax: 1500000,
      location: "Bangsar",
      preferredAreas: ["Bangsar"],
      propertyType: "Condo",
      bedrooms: 3,
      financing: "unknown",
      timelineDays: 180,
      timeline: "Flexible",
    },
    conversation: nurulConversation,
    timelineEvents: [
      { id: "te-n-1", type: "inquiry", title: "WhatsApp seller inquiry received", createdAt: t(900) },
    ],
  },
  {
    id: "marcus-lim",
    name: "Marcus Lim",
    phoneMasked: "+60 16-**** 2290",
    source: "WhatsApp",
    channel: "whatsapp",
    intent: "renter",
    location: "Bukit Bintang",
    preferredAreas: ["Bukit Bintang"],
    budget: "RM4,500/month",
    budgetLabel: "RM4,500/month",
    budgetMax: 4500,
    propertyType: "Condo",
    bedrooms: 2,
    financing: "unknown",
    timeline: "1–3 months",
    score: 42,
    scoreLabel: "Nurture",
    status: "nurture",
    conversationStatus: "ai_handling",
    assignedAgent: undefined,
    aiSummary: "Marcus is a renter looking near Bukit Bintang around RM4.5k per month. He asked about MRT access and has not provided a timeline or budget confirmation.",
    nextBestAction: "Answer the MRT question and ask for monthly budget and move-in window.",
    callStatus: "not_requested",
    lastActivity: marcusConversation[marcusConversation.length - 1].createdAt,
    qualification: {
      budgetMax: 4500,
      location: "Bukit Bintang",
      preferredAreas: ["Bukit Bintang"],
      propertyType: "Condo",
      bedrooms: 2,
      financing: "unknown",
      timelineDays: 90,
      timeline: "1–3 months",
    },
    conversation: marcusConversation,
    timelineEvents: [
      { id: "te-m-1", type: "inquiry", title: "WhatsApp inquiry received", createdAt: t(2100) },
    ],
  },
  {
    id: "farah-aziz",
    name: "Farah Aziz",
    phoneMasked: "+60 14-**** 8833",
    source: "WhatsApp",
    channel: "whatsapp",
    intent: "buyer",
    location: "Shah Alam",
    preferredAreas: ["Shah Alam"],
    budget: "RM900k",
    budgetLabel: "Below RM900k",
    budgetMax: 900000,
    propertyType: "Terrace house",
    bedrooms: 4,
    financing: "unknown",
    timeline: "Unknown",
    score: 60,
    scoreLabel: "Warm",
    status: "booked",
    conversationStatus: "ai_handling",
    assignedAgent: undefined,
    aiSummary: "Farah is looking for a 4-bedroom house in Shah Alam below RM900k. She reached out in Bahasa Melayu, selected Shah Alam Family Residence, and confirmed a viewing.",
    nextBestAction: "Send the property brochure before the viewing and offer a follow-up call.",
    callStatus: "not_requested",
    lastActivity: farahConversation[farahConversation.length - 1].createdAt,
    qualification: {
      budgetMax: 900000,
      location: "Shah Alam",
      preferredAreas: ["Shah Alam"],
      propertyType: "Terrace house",
      bedrooms: 4,
      financing: "unknown",
      timelineDays: 365,
      timeline: "Unknown",
      viewingSelected: true,
    },
    conversation: farahConversation,
    recommendedListings: [findListing("shah-alam-family-residence")],
    bookedViewing: allViewings.find((v) => v.bookingId === "bkg-003"),
    timelineEvents: [
      { id: "te-f-1", type: "inquiry", title: "Bahasa Melayu WhatsApp inquiry received", createdAt: t(120) },
      { id: "te-f-2", type: "viewing_booked", title: "Viewing confirmed: Thursday 5:00 PM", createdAt: t(116) },
    ],
  },
];

export const initialKnowledgeSources: KnowledgeSource[] = [
  {
    id: "ks-1",
    name: "KLCC_Residences_Brochure.pdf",
    category: "Property brochure",
    scope: "KLCC Residences",
    status: "Ready",
    version: "1.0",
    lastUpdated: t(2880),
    enabled: true,
    size: "2.4 MB",
    simulated: true,
  },
  {
    id: "ks-2",
    name: "Listings_August_2026.csv",
    category: "Inventory",
    scope: "All listings",
    status: "Ready",
    version: "1.0",
    lastUpdated: t(1440),
    enabled: true,
    size: "156 KB",
    simulated: true,
  },
  {
    id: "ks-3",
    name: "Buyer_FAQ_EN_BM.md",
    category: "FAQ",
    scope: "All buyer chats",
    status: "Ready",
    version: "1.0",
    lastUpdated: t(7200),
    enabled: true,
    size: "42 KB",
    simulated: true,
  },
  {
    id: "ks-4",
    name: "Viewing_and_Handoff_SOP.pdf",
    category: "Agency policy",
    scope: "All conversations",
    status: "Ready",
    version: "1.0",
    lastUpdated: t(10080),
    enabled: true,
    size: "1.1 MB",
    simulated: true,
  },
  {
    id: "ks-5",
    name: "NAPIC_KL_Transaction_Data.csv",
    category: "Market data",
    scope: "Kuala Lumpur",
    status: "Ready",
    version: "1.0",
    lastUpdated: t(4320),
    enabled: true,
    size: "890 KB",
    simulated: true,
  },
];

export const initialAgentRules: AgentRule[] = [
  {
    id: "rule-1",
    title: "Confirm availability before claiming a unit is available",
    instruction: "Never state that a unit is available unless an approved inventory source confirms it.",
    priority: "High",
    category: "Compliance",
    enabled: true,
    createdAt: t(10080),
    updatedAt: t(10080),
  },
  {
    id: "rule-2",
    title: "Do not guarantee financial or legal outcomes",
    instruction: "Never guarantee loan approval, investment returns, rental yield, legal outcomes, or price appreciation.",
    priority: "High",
    category: "Compliance",
    enabled: true,
    createdAt: t(10080),
    updatedAt: t(10080),
  },
  {
    id: "rule-3",
    title: "Escalate regulated questions to a human",
    instruction: "For legal, tax, loan, deposit, contract, or other regulated questions, provide general information only and offer human-agent handoff.",
    priority: "High",
    category: "Escalation",
    enabled: true,
    createdAt: t(10080),
    updatedAt: t(10080),
  },
  {
    id: "rule-4",
    title: "Offer a viewing to high-intent leads",
    instruction: "For leads scored at 80 or above, offer a viewing during the same conversation.",
    priority: "Medium",
    category: "Booking",
    enabled: true,
    createdAt: t(10080),
    updatedAt: t(10080),
  },
  {
    id: "rule-5",
    title: "Reply in the customer's language",
    instruction: "Reply in English or Bahasa Melayu based on the customer's latest message.",
    priority: "Medium",
    category: "Language",
    enabled: true,
    createdAt: t(10080),
    updatedAt: t(10080),
  },
  {
    id: "rule-6",
    title: "Stop autonomous qualification when human is requested",
    instruction: "If the customer requests a human agent, stop autonomous qualification and assign the lead to a human agent.",
    priority: "High",
    category: "Escalation",
    enabled: true,
    createdAt: t(10080),
    updatedAt: t(10080),
  },
];
