import {
  Listing,
  ViewingSlot,
  Lead,
  ConversationMessage,
} from "./types";

export const listings: Listing[] = [
  {
    id: "klcc-residences-3br",
    name: "KLCC Residences",
    location: "Jalan Sultan Ismail, Kuala Lumpur",
    price: 780000,
    priceDisplay: "RM780,000",
    beds: 3,
    baths: 2,
    sqft: 1180,
    description: "High-floor city-view unit, 8 minutes from KLCC.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    badge: "Best Match",
  },
  {
    id: "bukit-bintang-suite-3br",
    name: "Bukit Bintang Suite",
    location: "Bukit Bintang, Kuala Lumpur",
    price: 795000,
    priceDisplay: "RM795,000",
    beds: 3,
    baths: 2,
    sqft: 1120,
    description: "Walkable to retail, dining, and transit.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    badge: "New Listing",
  },
];

export function getViewingSlots(): ViewingSlot[] {
  const now = new Date();
  const slots: ViewingSlot[] = [
    {
      id: "slot-tomorrow-15",
      label: "Tomorrow, 3:00 PM",
      appointmentAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 15, 0).toISOString(),
    },
    {
      id: "slot-wednesday-11",
      label: "Wednesday, 11:00 AM",
      appointmentAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 3, 11, 0).toISOString(),
    },
    {
      id: "slot-thursday-17",
      label: "Thursday, 5:00 PM",
      appointmentAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 4, 17, 0).toISOString(),
    },
  ];
  return slots;
}

const aishaConversation: ConversationMessage[] = [
  {
    id: "msg-1",
    role: "agent",
    content: "Hi! I’m KeyNest, your AI property concierge. I can help you find a home, arrange a viewing, or connect you with an agent. What are you looking for today?",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "msg-2",
    role: "user",
    content: "Hi, I’m looking for a 3-bedroom condo near KLCC, budget under RM800k.",
    createdAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
  },
  {
    id: "msg-3",
    role: "agent",
    content: "Great — I can help with that. Are you already pre-approved for financing, or would you be buying with cash?",
    createdAt: new Date(Date.now() - 1000 * 60 * 27).toISOString(),
  },
  {
    id: "msg-4",
    role: "user",
    content: "Yes, approved up to RM850k.",
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: "msg-5",
    role: "agent",
    content: "Perfect. Which area would you prefer most: KLCC, Bukit Bintang, or Mont Kiara? And when are you hoping to move?",
    createdAt: new Date(Date.now() - 1000 * 60 * 24).toISOString(),
  },
  {
    id: "msg-6",
    role: "user",
    content: "KLCC or Bukit Bintang. Within 2 months.",
    createdAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
  },
  {
    id: "msg-7",
    role: "agent",
    content: "Thanks, Aisha. I found two 3-bedroom condos that fit your budget and timeline. Which one would you like to view?",
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    listings,
    actions: ["Lead qualified", "Matched 2 listings"],
  },
  {
    id: "msg-8",
    role: "user",
    content: "I’ll view KLCC Residences.",
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "msg-9",
    role: "agent",
    content: "Excellent choice. I can arrange a viewing with the listing agent. Which time works best for you?",
    createdAt: new Date(Date.now() - 1000 * 60 * 17).toISOString(),
    slots: getViewingSlots(),
  },
  {
    id: "msg-10",
    role: "user",
    content: "Tomorrow, 3:00 PM works.",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "msg-11",
    role: "agent",
    content: "Viewing confirmed. A calendar invite and confirmation will be sent to Aisha.",
    createdAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    booking: {
      listing: listings[0],
      slot: getViewingSlots()[0],
    },
    actions: ["Viewing scheduled"],
  },
];

export const initialLeads: Lead[] = [
  {
    id: "aisha-rahman",
    name: "Aisha Rahman",
    source: "Website chat",
    intent: "Buyer",
    location: "KLCC / Bukit Bintang",
    budget: "Under RM800k",
    budgetMax: 800000,
    score: 85,
    status: "booked",
    lastActivity: aishaConversation[aishaConversation.length - 1].createdAt,
    qualification: {
      budgetMax: 800000,
      location: "KLCC / Bukit Bintang",
      propertyType: "Condo",
      bedrooms: 3,
      financing: true,
      timelineDays: 60,
    },
    conversation: aishaConversation,
    recommendedListings: listings,
    bookedViewing: {
      bookingId: "bkg-001",
      confirmed: true,
      appointmentAt: getViewingSlots()[0].appointmentAt,
      leadId: "aisha-rahman",
      listingId: listings[0].id,
      slotId: getViewingSlots()[0].id,
      listing: listings[0],
      slot: getViewingSlots()[0],
    },
    nextBestAction: "Viewing confirmed for tomorrow, 3:00 PM. Send listing brochure after viewing.",
  },
  {
    id: "daniel-tan",
    name: "Daniel Tan",
    source: "WhatsApp",
    intent: "Buyer",
    location: "Mont Kiara",
    budget: "RM1.2M",
    budgetMax: 1200000,
    score: 78,
    status: "qualified",
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    qualification: {
      budgetMax: 1200000,
      location: "Mont Kiara",
      propertyType: "Condo",
      bedrooms: 3,
      financing: true,
      timelineDays: 90,
    },
    conversation: [
      {
        id: "daniel-1",
        role: "agent",
        content: "Hi! How can I help with your property search today?",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      },
      {
        id: "daniel-2",
        role: "user",
        content: "I want a 3-bedroom condo in Mont Kiara, budget around RM1.2M.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4.5).toISOString(),
      },
      {
        id: "daniel-3",
        role: "agent",
        content: "Thanks, Daniel. I have several listings in Mont Kiara within your budget. Are you pre-approved?",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      },
    ],
    nextBestAction: "Share 3-bedroom Mont Kiara listings and ask for viewing availability.",
  },
  {
    id: "nurul-izzati",
    name: "Nurul Izzati",
    source: "PropertyGuru lead",
    intent: "Seller",
    location: "Bangsar",
    budget: "RM1.5M",
    budgetMax: 1500000,
    score: 64,
    status: "new",
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    qualification: {
      budgetMax: 1500000,
      location: "Bangsar",
      propertyType: "Condo",
      bedrooms: 3,
      financing: false,
      timelineDays: 120,
    },
    conversation: [
      {
        id: "nurul-1",
        role: "agent",
        content: "Hi! I can help you sell your property. Which area is it in?",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
      },
      {
        id: "nurul-2",
        role: "user",
        content: "I want to sell my Bangsar condo, asking around RM1.5M.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      },
    ],
    nextBestAction: "Collect unit details and arrange a valuation appointment.",
  },
  {
    id: "marcus-lim",
    name: "Marcus Lim",
    source: "Facebook ad",
    intent: "Renter",
    location: "Bukit Bintang",
    budget: "RM4,500/month",
    budgetMax: 4500,
    score: 42,
    status: "cold",
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    qualification: {
      budgetMax: 4500,
      location: "Bukit Bintang",
      propertyType: "Condo",
      bedrooms: 2,
      financing: false,
      timelineDays: 180,
    },
    conversation: [
      {
        id: "marcus-1",
        role: "agent",
        content: "Hi! Are you looking to rent or buy?",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
      },
      {
        id: "marcus-2",
        role: "user",
        content: "Just browsing rentals near Bukit Bintang, maybe RM4.5k.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      },
    ],
    nextBestAction: "Follow up in 2 weeks and send new rental listings.",
  },
];
